apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  selector:
    app: jekyll
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 30097